### ISSUE TITLE
Why we return Map for *put_all(Map *other) instead of void? 

### ISSUE THREAD

**Issue by angeliama98** [jjones-99/cs4500-sp2020-a1-part2-jones-tam#15]
From my understanding, put_all concat two maps together(without duplicate). But why we need to keep track of the pairs that have their keys been replaced? Could we just return void instead?

**Comment by jjones-99** [comment]
A void return type for a `put_all()` method would also be a valid design choice, just as you can have a `put()` method either return a replaced value or be void.

It's down to how the user might want to use a Map. When we thought about how we would want to use a Map, we thought it would be helpful to return another Map because of the two situations:

* If the user doesn't want to keep track of the replaced pairs, they can just throw them away once they have them. If the new Map is created during the main looping of `put_all()`, there isn't much of a time efficiency loss. Memory for that new Map would be allocated, yes, but then quickly deallocated.
* If the user wants to keep track of the replaced pairs, they have them. If we didn't return it, they would have to iterate over the arrays in a separate loop, likely in `m * n` time (if `m` and `n` are the sizes of the Maps) which might be a big blow to time efficiency.

We thought about that a lot and decided on returning the replaced pairs.

**Comment by angeliama98** [comment]
gotcha! Thanks for the explanation!
