### ISSUE TITLE
StrToStrMap class doesn't have size(). Whereas we have a test that use size() in line 152.

### ISSUE THREAD

**Issue by angeliama98** [jjones-99/cs4500-sp2020-a1-part2-jones-tam#22]
Could we add size() to API for StrToStrMap class?

**Comment by jsxtam** [comment]
`StrToStrMap` is a derived class from `Map` class as specified in line 104 of `map.h`:

`class StrToStrMap : public Map`

Thus, `StrToStrMap` inherits the methods from the base `Map` class so a `size()` method specifically for `StrToStrMap` is unnecessary because it can call the base `Map`'s `size()` method.
